### ISSUE TITLE
Problem loading savegame

### ISSUE THREAD

**Issue by HAHAYOUDEAD** [dommrogers/ModData#1]
so ModData worked just fine when I first saved the game and reloaded it from main menu, though threw some trampoline shit at me
but when I restarted the game, it would not load savegame at all
it doesn't go to loading screen, stays at main menu scene but changes the menu itself as if I'm already in game
when I removed ModData.dll and restarted it wouldn't even go to main menu, just hanged(might be unrelated)
but with next restart without ModData it returned to normal

When there's no data to load - it loads fine (either no data at all or no data for specific slot)

Also it doesn't matter if I'm trying to load custom data or not - it will stay at menu even if I don't have any mods using ModData at all

https://user-images.githubusercontent.com/46863862/221868373-454f8c4e-4eb6-425a-976c-887cda1e6d42.mp4

**Comment by HAHAYOUDEAD** [comment]
```
[13:08:57.496] System.IO.IOException: The process cannot access the file 'C:\SteamLibrary\steamapps\common\TheLongDark\Mods\ModData\sandbox3.moddata' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at ModData.ZipUtils.GetEntries(String filePath) in C:\REPOS\ModData\ModData\ZipUtils.cs:line 163
   at ModData.ModDataCore.LoadCache() in C:\REPOS\ModData\ModData\ModDataCore.cs:line 139
   at ModData.ModDataCore.InitModDataCore(String saveName) in C:\REPOS\ModData\ModData\ModDataCore.cs:line 22
   at ModData.ModDataPatches.ModData_GameManager_LoadSaveGameSlot.Prefix(String slotName, Int32 saveChangelistVersion) in C:\REPOS\ModData\ModData\Patches.cs:line 23
   at DMD<Il2Cpp.GameManager::LoadSaveGameSlot>(String slotName, Int32 saveChangelistVersion)
   at (il2cpp -> managed) LoadSaveGameSlot(IntPtr , Int32 , Il2CppMethodInfo* )
```
here's the error

**Comment by HAHAYOUDEAD** [comment]
doesn't happen anymore with newest ModComponent
